#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# ---------------------------------------------------------------------------
# Core application dependencies
# ---------------------------------------------------------------------------

# nRF Edge AI inference runtime and Axon NPU driver
CONFIG_NRF_EDGEAI=y

# nRF Edge AI dependencies
CONFIG_NRF_AXON=y
CONFIG_FPU=y

# Size of interlayer buffer to fit model
CONFIG_NRF_AXON_INTERLAYER_BUFFER_SIZE=6656

# Size of psum buffer to fit model
CONFIG_NRF_AXON_PSUM_BUFFER_SIZE=0

# ---------------------------------------------------------------------------
# Required peripherals
# ---------------------------------------------------------------------------


# Enable nrfx drivers #
CONFIG_NRFX_SAADC=y
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_TIMER=y



# Enable GPIO for LEDs and AUDIO for DMIC
CONFIG_GPIO=y
CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y

# ---------------------------------------------------------------------------
# Power management
# ---------------------------------------------------------------------------
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y


# ---------------------------------------------------------------------------
# Disable all debug and logging infrastructure
# ---------------------------------------------------------------------------
CONFIG_LOG=n
CONFIG_PRINTK=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_SHELL=n
CONFIG_BOOT_BANNER=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_ASSERT=n
CONFIG_DEBUG=n

# ---------------------------------------------------------------------------
# Library size reduction
# ---------------------------------------------------------------------------
CONFIG_CBPRINTF_NANO=y

# ---------------------------------------------------------------------------
# Compiler and linker optimizations
# ---------------------------------------------------------------------------
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
