#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Use no-BLE mode
CONFIG_BLE_MODE_NONE=y

# nRF Edge AI
CONFIG_NRF_EDGEAI=y
# nRF Edge AI dependencies
CONFIG_FPU=y

# Enable sensor, button and LED libraries
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_GPIO=y

# Power management
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Disable LED pulsing effect to save energy
CONFIG_LED_NOTIFICATION_BLINK=y

# Enable logging
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Compiler/linker optimizations
CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
